version: '3.4'
services:

  grafana:
    image: grafana/grafana:5.3.2
    command: --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  influxdb:
    image: influxdb:1.5.4
    environment: &env
      - API_URL=http://api:8000
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@postgres:5432
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: 'no'
    volumes:
      - influxdb-data:/var/lib/influxdb

    # networks:
    #   - gateway
    # labels:
    #   - traefik.docker.network=gateway
    #   - traefik.frontend.rule=PathPrefixStrip:/api
    #   - traefik.port=8000


image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - /srv/docker/influxdb/data:/var/lib/influxdb



volumes:
  influxdb-data:
    external: true

networks:
  gateway:
    external: true