version: '3.4'
services:
  app:
    build: .
    command: "gunicorn --bind 0.0.0.0:8000 app:app"
    image: &app app
    environment: &env
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@postgres:5432
    ports:
      - 8000:8000
    restart: 'no'
    volumes: ['./app:/app']

  db-migration:
    image: *app
    environment: *env
    command: [flask, db, upgrade]
    volumes: ['./app:/app']

  postgres:
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
    external: true
