version: '3.4'
services:

  traefik:
    image: traefik:1.7.4
    command: --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  grafana:
    image: grafana/grafana:5.3.2
    networks:
      - gateway
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.docker.network=gateway"
      - "traefik.frontend.rule=PathPrefix:/"


  chronograf:
    image: chronograf:1.5.0
    environment:
     - INFLUXDB_URL=http://influxdb:8086
    restart: 'no'
    networks:
      - gateway
    volumes:
      - chronograf-data:/var/lib/chronograf
    depends_on:
      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.frontend.rule=Host:chronograf.datalake.ninja"
      - "traefik.port=8888"

  influxdb:
    image: influxdb:1.5.4
    environment:
     - INFLUXDB_DATA_ENGINE=tsm1
     - INFLUXDB_REPORTING_DISABLED=false
     - INFLUXDB_HTTP_AUTH_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=password
    restart: 'no'
    networks:
      - gateway
    volumes:
      - influxdb-data:/var/lib/influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.frontend.rule=Host:influxdb.datalake.ninja"
      - "traefik.port=8086"

networks:
  - gateway

volumes:
  grafana-data:
    external: true
  chronograf-data:
    external: true
  influxdb-data:
    external: true

networks:
  gateway:
    external: true